### ISSUE TITLE
Ntuser.dat is being used by another process

### ISSUE THREAD

**Issue by l1ttlerain56** [TheJumpCloud/jumpcloud-ADMU#147] opened 2024-11-13 19:37 UTC
Hi there,

We've been using ADMU v2.5.0 without issue to migrate users. However, on one of our user's endpoints, the ADMU tool consistently fails due to it thinking that the AD user's ntuser.dat file is being used by another process. This happens while logged in as the local admin, and even after multiple reboots. Using sysinternals process explorer, I see no process that is utilizing that user's .dat file. Not sure what else to check for. Please advise.

Thank you!

**Comment by jworkmanjc** [comment] 2024-11-13 22:04
Hey @l1ttlerain56, I'd encourage you to actually use the latest version of the ADMU found in our releases page: https://github.com/TheJumpCloud/jumpcloud-ADMU/releases

Can you give that a shot and let me know if that works?

The NTUser.DAT file can be locked for so many reasons but technically what's happening on your system is (most likely) some application is leaving an open handle in memory, loading that user's registry when you attempt to migrate and not closing that handle correctly. 

The ADMU entirely relies on being able to close and open the user's registry to migrate the account. If you open up Registry Editor and check in the HKEY_USERS hive I bet you'll see the user's profile loaded before, and if not, during migration. It could be the case that an Anti-Virus or Data Protection application is holding on to your user's registry during migration and if that's the case you might want to try to run the tool with those disabled. 

Again, there are going to be multiple possibilities for the NTUser.DAT file being locked but generally you can narrow it down to one or two thing. Please try with the latest version, we've added a number of items to the tool since 2.5.0

**Comment by l1ttlerain56** [comment] 2024-11-13 22:27
Hi @jworkmanjc ,

Thanks for the quick reply! I'll give the new tool a try and let you know how it goes.

Thanks again.

**Comment by l1ttlerain56** [comment] 2024-11-15 17:57
Hey @jworkmanjc,

So running the latest version of the ADMU tool worked! However, the ADMU was giving an error stating that it could not find the JumpCloud user if I set the "Autobind User" checkbox. It prompted to choose an organization after I input my API key, then asked me again to choose an org again after I clicked Migrate, then errored stating it could not find the user. I just binded the user's account after the fact with no issue to get around that error.

Thanks again.

**Comment by jworkmanjc** [comment] 2024-11-18 15:52
Interesting, okay I'll take a look at the MTP migration workflow, there's a chance there's a bug if you can't find the user before migration. I should respond today if I can replicate that.

**Comment by jworkmanjc** [comment] 2024-11-18 16:06
Ah okay looks like there is an issue with the MTP user selection, we are working on some updates right now, I'll see if we can get that bug rolled into this sprint.

**Comment by jworkmanjc** [comment] 2024-12-11 15:37
#146 should resolve the issue with MTP organization and autobind prompt, [v2.7.9](https://github.com/TheJumpCloud/jumpcloud-ADMU/releases/tag/v2.7.9) contains the fix for that specific issue. I'm going to mark this closed. 

There **can** always be an issue with the NTUser.dat file being opened by another process if some process leaves an open handle in memory. Forcefully closing the file could result in data loss so I'm not interested in going down that route just yet. The best course of action if this is encountered is to fully restart, try again, if the issue is persistent then it's clear there's an application on the device holding on to that user's NTUser.dat file. The application needs to be identified and potentially closed in order to continue migration.

**Closed as completed by jworkmanjc** 2024-12-11 15:37 UTC
